# Generated by Django 6.0.7 on 2026-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nvr",
            name="password",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="camera",
            name="snapshot_url",
            field=models.CharField(
                blank=True,
                help_text="Override URL for fetching a JPEG snapshot. If blank, a TP-Link VIGI default is used.",
                max_length=500,
            ),
        ),
    ]
