# Generated by Django 6.0.7 on 2026-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_nvr_password_camera_snapshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvr',
            name='https_port',
            field=models.PositiveIntegerField(blank=True, help_text='HTTPS web port, often 443.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='management_port',
            field=models.PositiveIntegerField(blank=True, help_text='HTTP management port, often 80.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='openapi_port',
            field=models.PositiveIntegerField(blank=True, help_text='Open API / SDK port for snapshots and control.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='remote_stream_port',
            field=models.PositiveIntegerField(blank=True, help_text='Port used for remote video streams.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='rtsp_port',
            field=models.PositiveIntegerField(blank=True, help_text='RTSP port, often 554.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='service_port',
            field=models.PositiveIntegerField(blank=True, help_text='Cloud / service port.', null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='use_https',
            field=models.BooleanField(default=False, help_text='Use HTTPS for snapshot requests when possible.'),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='port',
            field=models.PositiveIntegerField(default=554, help_text='Legacy / fallback port.'),
        ),
    ]
