# Generated by Django 6.0 on 2026-09-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_onvif_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvr',
            name='channel_count',
            field=models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (10, '10'), (16, '16')], default=4, help_text='Number of channels available on this NVR.'),
        ),
    ]
