# Generated by Django 6.1.1 on 2026-09-14 21:04

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('frame_diff', 'OpenCV frame diff'), ('manual', 'Manual capture'), ('onvif', 'ONVIF event'), ('nvr_push', 'NVR OpenAPI push')], default='frame_diff', max_length=20)),
                ('image', models.ImageField(upload_to=devices.models._event_upload_to)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('motion_score', models.FloatField(blank=True, help_text='Fraction of the frame that changed (0-1). Empty for manual captures.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending analysis'), ('analyzed', 'Analyzed'), ('failed', 'Analysis failed')], default='pending', max_length=20)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('face_count', models.PositiveIntegerField(default=0)),
                ('best_face_width', models.PositiveIntegerField(default=0)),
                ('best_face_height', models.PositiveIntegerField(default=0)),
                ('blur_score', models.FloatField(blank=True, help_text='Laplacian variance of the largest face crop. Higher is sharper.', null=True)),
                ('quality', models.CharField(choices=[('unknown', 'Not analyzed'), ('usable', 'Usable for recognition'), ('no_face', 'No face detected'), ('too_small', 'Face too small'), ('too_blurry', 'Face too blurry')], default='unknown', max_length=20)),
                ('faces', models.JSONField(blank=True, default=list, help_text='Detected face boxes and labels.')),
                ('recognized', models.JSONField(blank=True, default=list, help_text='Names matched against Person references.')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='devices.camera')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status'], name='devices_mot_status_2291b5_idx'), models.Index(fields=['-detected_at'], name='devices_mot_detecte_34a2ad_idx')],
            },
        ),
    ]
