"""Turn Person into a proper identity record and add the auto-enrolment tables.

Written by hand rather than autogenerated: `Person.code` is unique with a
callable default, so it has to be added nullable, backfilled per row, and only
then made unique. A generated migration would apply one default to every
existing row and collide.

The backfill also moves reference directories from `persons/<name>` to
`persons/<code>`. DeepFace derives identity from the directory name, so leaving
them keyed on a mutable name means a rename silently breaks recognition.
"""

import uuid

from django.db import migrations, models
import django.db.models.deletion

import devices.models


def backfill_codes(apps, schema_editor):
    Person = apps.get_model("devices", "Person")
    for person in Person.objects.all():
        person.code = uuid.uuid4().hex[:12]
        person.save(update_fields=["code"])
        _move_reference_dir(person.name, person.code)


def _move_reference_dir(old_name, code):
    """Move persons/<name> to persons/<code> if the old directory exists."""
    if not old_name:
        return
    try:
        from pathlib import Path

        from django.conf import settings

        root = Path(settings.MEDIA_ROOT) / "persons"
        source, destination = root / old_name, root / code
        if source.exists() and source.is_dir() and not destination.exists():
            source.rename(destination)
    except OSError:
        # A failed move must not abort the schema change; recognition can be
        # restored by re-uploading a reference image.
        pass


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_motionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="code",
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.RunPython(backfill_codes, noop),
        migrations.AlterField(
            model_name="person",
            name="code",
            field=models.CharField(
                default=devices.models.new_identity_code,
                editable=False,
                help_text="Immutable key used as the reference directory name.",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="auto_created",
            field=models.BooleanField(
                default=False,
                help_text="Created by the recognizer from an unmatched face rather than uploaded.",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["name", "-created_at"]},
        ),
        migrations.CreateModel(
            name="FaceCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(default=devices.models.new_identity_code, editable=False, max_length=32, unique=True)),
                ("image", models.ImageField(upload_to=devices.models._candidate_upload_to)),
                ("sighting_count", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="face_candidates",
                        to="devices.camera",
                    ),
                ),
            ],
            options={"ordering": ["-last_seen_at"]},
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distance", models.FloatField(blank=True, help_text="Cosine distance to the reference.", null=True)),
                ("box", models.JSONField(blank=True, default=list)),
                (
                    "is_enrollment",
                    models.BooleanField(default=False, help_text="This capture is the one that created the person."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="devices.motionevent",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="devices.person",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="sighting",
            constraint=models.UniqueConstraint(fields=("event", "person"), name="unique_sighting_per_event"),
        ),
    ]
