# Generated by Django 6.1.1 on 2026-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_face_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionevent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When a user confirmed the verdict. Confirmed no-face events are purged by cleanup_events.', null=True),
        ),
    ]
