# Generated by Django 6.1.1 on 2026-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_motionevent_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionevent',
            name='persons',
            field=models.JSONField(blank=True, default=list, help_text='Person-shaped regions found by pedestrian detection (box x, y, w, h).'),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='quality',
            field=models.CharField(choices=[('unknown', 'Not analyzed'), ('usable', 'Usable for recognition'), ('person', 'Person seen, no usable face'), ('no_face', 'No face detected'), ('too_small', 'Face too small'), ('too_blurry', 'Face too blurry')], default='unknown', max_length=20),
        ),
    ]
