# Generated by Django 6.1.1 on 2026-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_motionevent_persons_alter_motionevent_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='confirmed',
            field=models.BooleanField(blank=True, help_text='User verdict on the match. Null = unreviewed, True = approved.', null=True),
        ),
    ]
