# Generated by Django 6.1.1 on 2026-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_sighting_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facecandidate',
            name='first_seen_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facecandidate',
            name='last_seen_at',
            field=models.DateTimeField(),
        ),
    ]
