# Generated by Django 6.1.1 on 2026-09-22 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_facecandidate_first_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motionevent',
            options={'ordering': ['-detected_at', 'rank']},
        ),
        migrations.AddField(
            model_name='motionevent',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Position within the sequence by usefulness for recognition; 0 is the best shot.'),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='sequence',
            field=models.CharField(blank=True, db_index=True, help_text='Frames captured during one continuous motion episode share this id.', max_length=32),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the frame was captured.'),
        ),
    ]
