# Generated by Django 6.0.7 on 2026-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_motionevent_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='show_image',
            field=models.BooleanField(default=True, help_text="Show this camera's image in the UI. Detection keeps running either way."),
        ),
    ]
