#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."
source "$SCRIPT_DIR/compose"

compose --profile motion up -d
compose --profile motion logs -f web
