from django.urls import path

from .views import (
    camera_create,
    camera_delete,
    camera_edit,
    camera_feed,
    camera_list,
    camera_recognize,
    camera_snapshot,
    camera_stream,
    event_analyze,
    event_annotated,
    event_capture,
    event_detail,
    event_image,
    event_list,
    nvr_create,
    nvr_delete,
    nvr_discover,
    nvr_edit,
    nvr_list,
    sensor_create,
    sensor_delete,
    sensor_edit,
    sensor_list,
)

app_name = "devices"

urlpatterns = [
    path("cameras/", camera_list, name="cameras"),
    path("cameras/add/", camera_create, name="camera_add"),
    path("cameras/<int:camera_id>/edit/", camera_edit, name="camera_edit"),
    path("cameras/<int:camera_id>/delete/", camera_delete, name="camera_delete"),
    path("cameras/<int:camera_id>/feed/", camera_feed, name="camera_feed"),
    path("cameras/<int:camera_id>/snapshot/", camera_snapshot, name="camera_snapshot"),
    path("cameras/<int:camera_id>/recognize/", camera_recognize, name="camera_recognize"),
    path("cameras/<int:camera_id>/stream/", camera_stream, name="camera_stream"),
    path("cameras/<int:camera_id>/capture/", event_capture, name="event_capture"),
    path("events/", event_list, name="events"),
    path("events/<int:event_id>/", event_detail, name="event_detail"),
    path("events/<int:event_id>/image/", event_image, name="event_image"),
    path("events/<int:event_id>/annotated/", event_annotated, name="event_annotated"),
    path("events/<int:event_id>/analyze/", event_analyze, name="event_analyze"),
    path("sensors/", sensor_list, name="sensors"),
    path("sensors/add/", sensor_create, name="sensor_add"),
    path("sensors/<int:sensor_id>/edit/", sensor_edit, name="sensor_edit"),
    path("sensors/<int:sensor_id>/delete/", sensor_delete, name="sensor_delete"),
    path("nvrs/", nvr_list, name="nvrs"),
    path("nvrs/add/", nvr_create, name="nvr_add"),
    path("nvrs/<int:nvr_id>/edit/", nvr_edit, name="nvr_edit"),
    path("nvrs/<int:nvr_id>/delete/", nvr_delete, name="nvr_delete"),
    path("nvrs/discover/", nvr_discover, name="nvr_discover"),
]
