from django.urls import path

from .views import (
    camera_create,
    camera_delete,
    camera_edit,
    camera_feed,
    camera_list,
    camera_recognize,
    camera_snapshot,
    camera_stream,
    candidate_delete,
    candidate_image,
    candidate_promote,
    event_analyze,
    event_annotated,
    event_bulk_delete,
    event_capture,
    event_cleanup_now,
    event_delete,
    event_detail,
    event_image,
    event_list,
    event_review,
    event_review_no_face,
    nvr_create,
    nvr_delete,
    nvr_discover,
    nvr_edit,
    nvr_list,
    person_add_reference,
    person_create,
    person_delete,
    person_delete_reference,
    person_detail,
    person_image,
    person_reference_image,
    person_list,
    person_name,
    person_update,
    sensor_create,
    sensor_delete,
    sensor_edit,
    sensor_list,
    sighting_approve,
    sighting_face,
    sighting_reject,
)

app_name = "devices"

urlpatterns = [
    path("cameras/", camera_list, name="cameras"),
    path("cameras/add/", camera_create, name="camera_add"),
    path("cameras/<int:camera_id>/edit/", camera_edit, name="camera_edit"),
    path("cameras/<int:camera_id>/delete/", camera_delete, name="camera_delete"),
    path("cameras/<int:camera_id>/feed/", camera_feed, name="camera_feed"),
    path("cameras/<int:camera_id>/snapshot/", camera_snapshot, name="camera_snapshot"),
    path("cameras/<int:camera_id>/recognize/", camera_recognize, name="camera_recognize"),
    path("cameras/<int:camera_id>/stream/", camera_stream, name="camera_stream"),
    path("cameras/<int:camera_id>/capture/", event_capture, name="event_capture"),
    path("events/", event_list, name="events"),
    path("events/review-no-face/", event_review_no_face, name="event_review_no_face"),
    path("events/bulk-delete/", event_bulk_delete, name="event_bulk_delete"),
    path("events/cleanup/", event_cleanup_now, name="event_cleanup_now"),
    path("events/<int:event_id>/", event_detail, name="event_detail"),
    path("events/<int:event_id>/image/", event_image, name="event_image"),
    path("events/<int:event_id>/annotated/", event_annotated, name="event_annotated"),
    path("events/<int:event_id>/analyze/", event_analyze, name="event_analyze"),
    path("events/<int:event_id>/review/", event_review, name="event_review"),
    path("events/<int:event_id>/delete/", event_delete, name="event_delete"),
    path("people/", person_list, name="people"),
    path("candidates/<int:candidate_id>/image/", candidate_image, name="candidate_image"),
    path("candidates/<int:candidate_id>/delete/", candidate_delete, name="candidate_delete"),
    path("candidates/<int:candidate_id>/promote/", candidate_promote, name="candidate_promote"),
    path("people/add/", person_create, name="person_add"),
    path("people/<int:person_id>/", person_detail, name="person_detail"),
    path("people/<int:person_id>/image/", person_image, name="person_image"),
    path("people/<int:person_id>/name/", person_name, name="person_name"),
    path("people/<int:person_id>/update/", person_update, name="person_update"),
    path("people/<int:person_id>/delete/", person_delete, name="person_delete"),
    path("people/<int:person_id>/references/add/", person_add_reference, name="person_add_reference"),
    path("people/<int:person_id>/references/<str:filename>/image/", person_reference_image, name="person_reference_image"),
    path("people/<int:person_id>/references/<str:filename>/delete/", person_delete_reference, name="person_delete_reference"),
    path("sightings/<int:sighting_id>/approve/", sighting_approve, name="sighting_approve"),
    path("sightings/<int:sighting_id>/reject/", sighting_reject, name="sighting_reject"),
    path("sightings/<int:sighting_id>/face/", sighting_face, name="sighting_face"),
    path("sensors/", sensor_list, name="sensors"),
    path("sensors/add/", sensor_create, name="sensor_add"),
    path("sensors/<int:sensor_id>/edit/", sensor_edit, name="sensor_edit"),
    path("sensors/<int:sensor_id>/delete/", sensor_delete, name="sensor_delete"),
    path("nvrs/", nvr_list, name="nvrs"),
    path("nvrs/add/", nvr_create, name="nvr_add"),
    path("nvrs/<int:nvr_id>/edit/", nvr_edit, name="nvr_edit"),
    path("nvrs/<int:nvr_id>/delete/", nvr_delete, name="nvr_delete"),
    path("nvrs/discover/", nvr_discover, name="nvr_discover"),
]
